name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Pull Docker image and run
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker pull leonsr/docker_royal_test:latest 
        docker stop node_app || true
        docker rm node_app || true
        docker run -d --name node_app -p 3000:3000 leonsr/docker_royal_test:latest:latest