name: Continuous Integration

on:
  workflow_call:
    inputs:
      commitAuthor:
        required: true
        type: string
      repositoryOwner:
        required: true
        type: string
      repositoryName:
        required: true
        type: string
      branchName:
        required: true
        type: string

jobs:
    build-and-push:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Build Docker image
              run: |
                docker build -f .docker/Dockerfile -t leonsr/docker_royal_test:latest -t leonsr/docker_royal_test:${GITHUB_SHA} .

            - name: Push Docker image
              run: |
                echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
                docker push leonsr/docker_royal_test:latest
                docker push leonsr/docker_royal_test:${GITHUB_SHA}
                        