name: Full Workflow

on: 
  push:
    branches:
      - main

jobs:
  trigger-ci:
    runs-on: self-hosted
    steps:
    - name: Trigger Continuous Integration
      uses: actions/github-script@v5
      with:
        script: |
          github.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'ci.yml',
            ref: 'main',
          })
        github-token: ${{ secrets.PAT }}
  
  trigger-cd:
    needs: trigger-ci
    runs-on: self-hosted
    steps:
    - name: Trigger Continuous Deployment
      uses: actions/github-script@v5
      with:
        script: |
          github.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'cd.yml',
            ref: 'main',
          })
        github-token: ${{ secrets.PAT }}
